git.pepabo.com:
    user: donokun
    git_protocol: https
    users:
        donokun:
github.com:
    user: naoyafurudono
    git_protocol: https
    users:
        naoyafurudono:
        naoya-furudono_pepabo:
