#!/bin/sh

# ステージされた追加/変更ファイル一覧を取得
files=$(git diff --cached --name-only --diff-filter=AM)

# 末尾改行を補完する処理
for f in $files; do
    echo "... $f"
    if [ -f "$f" ] && git grep -Iq . -- "$f"; then  # テキストファイルのみ対象
        echo "text: $f"
        if [ "$(tail -c2 "$f")" != "" ] && [ "$(tail -c2 "$f")" != $'\n' ]; then
            echo >> "$f"      # 末尾に改行を追加
            git add "$f"      # 修正をステージに追加
            echo "added newline: $f"
        fi
    fi
done

exit 0  # 通常のコミット続行

