#!/bin/bash

# ステージされた追加/変更ファイル一覧を取得
files=$(git diff --cached --name-only --diff-filter=AM)

# textfmt がなければ exit
if ! command -v textfmt &>/dev/null; then
    echo "textfmt could not be found"
    echo "go install github.com/naoyafurudono/textfmt@latest"
    exit 1
fi

# 末尾改行を補完する処理
for f in $files; do
    if [ -f "$f" ] && git grep -Iq . -- "$f"; then # テキストファイルのみ対象
        textfmt "$f"
        git add "$f" # 修正をステージに追加
    fi
done

exit 0 # 通常のコミット続行
